default_install_hook_types: [pre-commit, post-commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: file-contents-sorter
        args: [--unique]
        files: ^\.gitattributes$|^\.gitignore$|^requirements-dev\.txt$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint

  - repo: https://github.com/assorted-pre-commit-hooks/copyright
    rev: v0.7
    hooks:
      - id: copyright

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy

  - repo: https://github.com/assorted-pre-commit-hooks/version-tag
    rev: v0.1
    hooks:
      - id: version-tag
